### ISSUE TITLE
[Feature] - Nginx Container for serving 

### ISSUE THREAD

**Issue by felixfaisal** [kaiwalyakoparkar/Find-Me-Resource#58]
### Is your feature request related to a problem? Please describe.
Setting up docker-compose for Nginx container to serve the HTML 

### Describe the solution you'd like
Create a yaml file and create volumes for linters to run without a hitch 

### Describe alternatives you've considered
We could use other servers like Apache or Actix Web. But I feel Nginx is beginner friendly and has features that will help your project and in the future you can use multiple 

### Additional context
![image](https://user-images.githubusercontent.com/42486737/122387027-0fa86f80-cf8c-11eb-8905-21c1d0f216c3.png)
An example of nginx being used for React and Django, So by this you'll learn to create Nginx image for bigger microservices architecture

**Comment by kaiwalyakoparkar** [comment]
Oh! ok but is it okay for my project as I only have HTML, CSS, & JS as of now?
